### ISSUE TITLE
Questions about the Evaluation: Multiple Predicted Nodes with the Same Sentence

### ISSUE THREAD

**Issue by yangky11** [allenai/entailment_bank#8]
Hi,

I find a potential bug when running the evaluation code on the following example:
Hypothesis: `a complete revolution of earth around the sun takes an earth year`
Ground truth proof: `sent18 & sent25 & sent3 -> int1: earth revolving the sun is an example of a planet revolving around its star; int1 & sent17 -> hypothesis;`
Predicted proof `sent17 & sent18 -> int1: a complete revolution of earth around the sun takes an earth year; int1 & sent25 -> hypothesis`

Looking at the intermediates, it produces an F1 score of 0.5 and an accuracy of 1, which does not make sense since the accuracy should be 1 if and only if the F1 score is 1. 

The problem is that `int1` in the predicted proof is identical to the hypothesis. So both `int1` and `hypothesis` in the predicted proof are aligned to `hypothesis` in the ground truth proof. The dictionary `prediction_to_aligned_gold ` here has only 1 element whereas `id_to_int_gold` and `id_to_int_pred` have 2. When calculating the F1 score, should we consider this case as having 1 true positive or 2 true positives? Also, what's the correct accuracy for this example?
https://github.com/allenai/entailment_bank/blob/1a6ab0fb87574e4996c8badab7d5301ea4d9472f/utils/eval_utils.py#L541-L545

**Comment by bhavanadalvi** [comment]
Thanks @yangky11 for detecting this.  
Yes, we can align multiple predicted intermediates to same gold intermediate. This choice was made so that all the predicted nodes are evaluated. This also accommodates cases where model might generate lengthier or shorter proofs w.r.t. gold proof, but the reasoning is still correct. In the end we compute precision, recall and F1 based on this alignment. 

You are right that INT AllCorrect should not be =1, if F1 < 1. I have debugged and fixed this issue in the latest commit. I will also update the arxiv paper and add note about resultant changes in INT AcllCorrect numbers.
https://github.com/allenai/entailment_bank/commit/76efc47b5aafc55322ff48f1abd3221a08b74de8
